# Generated by Django 5.2.16 on 2026-07-20 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='First question, truncated — set once, never re-derived', max_length=200, null=True)),
                ('scope_type', models.CharField(choices=[('document', 'Article or video'), ('topic', 'Topic'), ('kb', 'Whole knowledge base')], default='kb', max_length=20)),
                ('scope_content_type', models.CharField(blank=True, choices=[('article', 'Article'), ('youtube_video', 'YouTube video')], max_length=20, null=True)),
                ('scope_content_id', models.BigIntegerField(blank=True, null=True)),
                ('scope_topic_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list, help_text="Resolved Citation dicts, empty for role='user'")),
                ('grounded', models.BooleanField(blank=True, help_text="Null for role='user' — grounded only applies to assistant turns", null=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('total_tokens', models.IntegerField(blank=True, help_text='Groq usage.total_tokens when available — cost telemetry, not always populated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.chatconversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', '-last_active_at'], name='ix_chat_conv_user_active'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ix_chat_msg_conv_created'),
        ),
    ]
