# Generated by Django 5.2.16 on 2026-08-08 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(max_length=20)),
                ('privacy_policy_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'terms_acceptances',
                'indexes': [models.Index(fields=['user', '-accepted_at'], name='ix_terms_acceptance_user')],
            },
        ),
    ]
