"""M10: extend sources for user submissions, add person_entities

Revision ID: 180c4f7d1297
Revises: 6ce3eac6ed9e
Create Date: 2026-07-15 22:18:54.022615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180c4f7d1297'
down_revision: Union[str, Sequence[str], None] = '6ce3eac6ed9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_entities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment="The person Entity this footprint belongs to (entities.entity_type should be 'person', not enforced at the DB level here)"),
    sa.Column('footprint_type', sa.String(length=20), nullable=False, comment="'blog' | 'youtube' | 'github' | 'substack' — a UI/data-modeling label; blog/github/substack all scrape via the same generic RSS/Atom mechanism (RssFeedScraper), only youtube uses a distinct per-channel adapter"),
    sa.Column('source_id', sa.BigInteger(), nullable=True, comment='The Source Registry row that actually gets scraped for this footprint — null until the footprint has been validated/registered'),
    sa.Column('external_identifier', sa.String(length=500), nullable=True, comment='Raw identifier as submitted (feed URL, YouTube channel id, GitHub username, etc.) — kept even after source_id is set, for display/audit'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("footprint_type IN ('blog', 'youtube', 'github', 'substack')", name='ck_person_entities_footprint_type'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'footprint_type', name='uq_person_entity_footprint')
    )
    op.add_column('sources', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='Django users.id of whoever submitted this source — plain reference, no DB-level FK (different ORM/metadata). Null for the 9 admin-seeded sources.'))
    op.add_column('sources', sa.Column('visibility', sa.String(length=20), server_default='global', nullable=False, comment="'global' (admin-seeded, on by default for everyone) or 'user' (submitted by a user, opt-in via user_source_subscriptions)"))
    op.add_column('sources', sa.Column('feed_url', sa.String(length=2048), nullable=True, comment="Canonicalization key for user-submitted RSS sources — the exact feed URL, so re-submitting an already-known feed reuses the existing Source row instead of duplicating it. Null for admin-seeded rows (their feeds live inside config['feeds'], several per row)."))
    op.add_column('sources', sa.Column('validation_status', sa.String(length=20), nullable=True, comment="AI-relevance gate outcome for user-submitted sources: 'accepted' | 'accepted_low_trust' | 'rejected'. Null for admin-seeded rows (never gated)."))
    op.add_column('sources', sa.Column('validation_score', sa.Float(), nullable=True, comment="Mean cosine similarity vs. the AI-corpus centroid at last validation — the relevance gate's raw score, not just its accept/reject decision"))
    op.add_column('sources', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True, comment='When the relevance gate last ran for this source — re-validated monthly per the roadmap (feeds drift over time)'))
    op.create_index('ix_sources_created_by', 'sources', ['created_by'], unique=False)
    op.create_index('ix_sources_visibility', 'sources', ['visibility'], unique=False)
    op.create_unique_constraint(None, 'sources', ['feed_url'])
    # ### end Alembic commands ###

    # NOT autogenerated — Alembic's autogenerate does not reliably diff CHECK
    # constraints on existing tables (confirmed live: these two were defined
    # in app/database/models/source.py's __table_args__ but silently absent
    # from the autogenerate output above). Added by hand; see
    # .wolf/buglog.json for this class of gotcha (also hit pgvector imports,
    # pipeline-017).
    op.create_check_constraint(
        "ck_sources_visibility", "sources", "visibility IN ('global', 'user')",
    )
    op.create_check_constraint(
        "ck_sources_validation_status", "sources",
        "validation_status IS NULL OR validation_status IN ('accepted', 'accepted_low_trust', 'rejected')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_sources_validation_status", "sources", type_="check")
    op.drop_constraint("ck_sources_visibility", "sources", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='unique')
    op.drop_index('ix_sources_visibility', table_name='sources')
    op.drop_index('ix_sources_created_by', table_name='sources')
    op.drop_column('sources', 'validated_at')
    op.drop_column('sources', 'validation_score')
    op.drop_column('sources', 'validation_status')
    op.drop_column('sources', 'feed_url')
    op.drop_column('sources', 'visibility')
    op.drop_column('sources', 'created_by')
    op.drop_table('person_entities')
    # ### end Alembic commands ###
