"""m10_articles_source_fk

Revision ID: 43e140a8efba
Revises: 180c4f7d1297
Create Date: 2026-07-15 23:05:39.150591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e140a8efba'
down_revision: Union[str, Sequence[str], None] = '180c4f7d1297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually added: seed the 2 legacy BlogScraper keys into the Source
    # Registry BEFORE adding the FK below, since existing `articles` rows
    # with source='blog_openai'/'blog_anthropic' would otherwise fail FK
    # validation (autogenerate never emits data changes, only schema diffs).
    op.execute(
        """
        INSERT INTO sources (key, name, category, adapter_type, handler, config, schedule_hours, is_active, visibility)
        VALUES
            ('blog_openai', 'OpenAI Blog', 'media', 'rss', NULL,
             '{"note": "Registry row for FK integrity only - BlogScraper (hardcoded/legacy) does not read this row."}'::jsonb,
             24, true, 'global'),
            ('blog_anthropic', 'Anthropic Blog', 'media', 'rss', NULL,
             '{"note": "Registry row for FK integrity only - BlogScraper (hardcoded/legacy) does not read this row."}'::jsonb,
             24, true, 'global')
        ON CONFLICT (key) DO NOTHING
        """
    )

    # Manually added: autogenerate does not reliably diff CHECK constraints
    # on existing tables (same gotcha hit in 180c4f7d1297) — the old
    # hardcoded 10-value whitelist must be dropped explicitly.
    op.drop_constraint("ck_articles_source", "articles", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_articles_source', 'articles', 'sources', ['source'], ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_articles_source', 'articles', type_='foreignkey')
    # ### end Alembic commands ###

    # Manually added: restore the pre-M10 hardcoded whitelist.
    op.create_check_constraint(
        "ck_articles_source",
        "articles",
        "source IN ("
        "'blog_openai', 'blog_anthropic', 'arxiv', 'github_release', "
        "'reddit', 'government_us', 'government_uk', 'government_nist', "
        "'funding_crunchbase', 'huggingface_model'"
        ")",
    )

    # Manually added: remove the registry-only rows seeded in upgrade().
    op.execute("DELETE FROM sources WHERE key IN ('blog_openai', 'blog_anthropic')")
