"""youtube_videos content comment: full transcript capture

Revision ID: 5565f1755db8
Revises: b3a44ff1b6b1
Create Date: 2026-07-15 01:07:46.506156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5565f1755db8'
down_revision: Union[str, Sequence[str], None] = 'b3a44ff1b6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_videos', 'content',
               existing_type=sa.TEXT(),
               comment='Full transcript text (M7: captured in full — not truncated at scrape time)',
               existing_comment='Full transcript text (truncated to max_transcript_chars)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_videos', 'content',
               existing_type=sa.TEXT(),
               comment='Full transcript text (truncated to max_transcript_chars)',
               existing_comment='Full transcript text (M7: captured in full — not truncated at scrape time)',
               existing_nullable=True)
    # ### end Alembic commands ###
