"""m11_trends_and_trend_reports

Revision ID: 694b5a3aa3a4
Revises: 43e140a8efba
Create Date: 2026-07-17 19:53:57.161841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '694b5a3aa3a4'
down_revision: Union[str, Sequence[str], None] = '43e140a8efba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False, comment='Monday of the covered week (UTC)'),
    sa.Column('narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of claim-units shown to users: {headline, body, trend_dimension, trend_key, citations: [{content_type, content_id}, ...]}'),
    sa.Column('raw_narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Pre-grounding-filter LLM output, for spot-check auditing only — never rendered to users'),
    sa.Column('narrative_version', sa.String(length=50), nullable=False, comment="Prompt/schema version, same convention as EnrichmentAgent's enrichment_version"),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', name='uq_trend_reports_week_start_date')
    )
    op.create_table('trends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False, comment="'topic' | 'entity'"),
    sa.Column('key', sa.String(length=200), nullable=False, comment="TaxonomyTopic.slug for 'topic', str(Entity.id) for 'entity'"),
    sa.Column('date', sa.Date(), nullable=False, comment='UTC calendar day this row covers'),
    sa.Column('mention_count', sa.Integer(), nullable=False, comment='Distinct content items mentioning this topic/entity, published on `date`'),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('baseline_stddev', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=True, comment="NULL means insufficient history/volume to judge (see run_trend_computation_phase's guards) — never a fabricated number"),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dimension IN ('topic', 'entity')", name='ck_trends_dimension'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'key', 'date', name='uq_trends_dimension_key_date')
    )
    op.create_index('ix_trends_date_is_trending', 'trends', ['date', 'is_trending'], unique=False)
    op.create_index('ix_trends_dimension_key_date', 'trends', ['dimension', 'key', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trends_dimension_key_date', table_name='trends')
    op.drop_index('ix_trends_date_is_trending', table_name='trends')
    op.drop_table('trends')
    op.drop_table('trend_reports')
    # ### end Alembic commands ###
