"""add user_profile_vectors and user_rankings score_version/features

Revision ID: 6ce3eac6ed9e
Revises: 6e3b60ce43c9
Create Date: 2026-07-15 05:48:45.244192

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ce3eac6ed9e'
down_revision: Union[str, Sequence[str], None] = '6e3b60ce43c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_vectors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Django users.id — plain reference, no DB-level FK (different ORM/metadata)'),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Which embedding model produced the source vectors this mean was built from'),
    sa.Column('sample_size', sa.Integer(), nullable=False, comment='How many engagement events contributed to this vector — 0 means cold start (no engagement yet)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_user_profile_vector_user')
    )
    op.add_column('user_rankings', sa.Column('score_version', sa.String(length=50), server_default='v0-curatoragent', nullable=False, comment='Which ranker/scoring-formula version produced this row — lets the eval harness compare versions and a formula change invalidate cleanly'))
    op.add_column('user_rankings', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Exact per-item scoring feature snapshot (interest/topic match, quality score, freshness, source affinity, novelty penalty, MMR-selected flag, exploration-slice flag) — the eval harness and any future learned ranker train on this, not just relevance_score'))
    op.alter_column('user_rankings', 'reasoning',
               existing_type=sa.TEXT(),
               comment="Templated 'why recommended' explanation built from the scoring features that won this rank — shown verbatim as 'Recommended because...'",
               existing_comment="CuratorAgent's own stated reasoning for this rank — shown verbatim as 'Recommended because...'",
               existing_nullable=False)
    op.alter_column('user_rankings', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this ranking was produced — replaced wholesale on each ranking run, not accumulated',
               existing_comment='When this ranking was produced — replaced wholesale on each digest run, not accumulated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_rankings', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this ranking was produced — replaced wholesale on each digest run, not accumulated',
               existing_comment='When this ranking was produced — replaced wholesale on each ranking run, not accumulated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_rankings', 'reasoning',
               existing_type=sa.TEXT(),
               comment="CuratorAgent's own stated reasoning for this rank — shown verbatim as 'Recommended because...'",
               existing_comment="Templated 'why recommended' explanation built from the scoring features that won this rank — shown verbatim as 'Recommended because...'",
               existing_nullable=False)
    op.drop_column('user_rankings', 'features')
    op.drop_column('user_rankings', 'score_version')
    op.drop_table('user_profile_vectors')
    # ### end Alembic commands ###
