"""add content intelligence layer tables

Revision ID: 6e3b60ce43c9
Revises: 5565f1755db8
Create Date: 2026-07-15 02:42:16.580110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e3b60ce43c9'
down_revision: Union[str, Sequence[str], None] = '5565f1755db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_clusters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_enrichment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video'"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('content_category', sa.String(length=30), nullable=False, comment="'research' | 'product-launch' | 'tutorial' | 'opinion' | 'funding' | 'announcement' | 'tooling' | 'other'"),
    sa.Column('technical_depth', sa.Integer(), nullable=False, comment='1 (accessible) - 5 (expert/research-level)'),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List[str] — 3-5 short bullet takeaways'),
    sa.Column('technical_details', sa.Text(), nullable=False),
    sa.Column('business_angle', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('enrichment_version', sa.String(length=50), nullable=False, comment="Prompt/schema version tag (app/agents/enrichment_agent.py's ENRICHMENT_VERSION) — distinguishes e.g. live-ingest vs. backfill passes"),
    sa.Column('enriched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_category IN ('research', 'product-launch', 'tutorial', 'opinion', 'funding', 'announcement', 'tooling', 'other')", name='ck_content_enrichment_category'),
    sa.CheckConstraint('technical_depth BETWEEN 1 AND 5', name='ck_content_enrichment_depth'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', name='uq_content_enrichment')
    )
    op.create_table('content_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video'"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_version', sa.String(length=50), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Exact feature vector that produced `score` — the point of this table per Principle 7, not just the score itself'),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', name='uq_content_score')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False, comment="'company' | 'model' | 'person' | 'technology'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('company', 'model', 'person', 'technology')", name='ck_entities_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'entity_type', name='uq_entity_name_type')
    )
    op.create_table('taxonomy_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True, comment="Small fixed grouping for UI display, e.g. 'core-ai' | 'policy' | 'applications' | 'business' | 'infrastructure'"),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('content_cluster_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video'"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('similarity_to_centroid', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['content_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', name='uq_content_cluster_member')
    )
    op.create_index('ix_content_cluster_members_cluster', 'content_cluster_members', ['cluster_id'], unique=False)
    op.create_table('content_entities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video'"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('mention_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', 'entity_id', name='uq_content_entity')
    )
    op.create_index('ix_content_entities_content', 'content_entities', ['content_type', 'content_id'], unique=False)
    op.create_index('ix_content_entities_entity', 'content_entities', ['entity_id'], unique=False)
    op.create_table('content_topics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video'"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('taxonomy_topic_id', sa.BigInteger(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_topic_id'], ['taxonomy_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', 'taxonomy_topic_id', name='uq_content_topic')
    )
    op.create_index('ix_content_topics_content', 'content_topics', ['content_type', 'content_id'], unique=False)
    op.create_index('ix_content_topics_topic', 'content_topics', ['taxonomy_topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_topics_topic', table_name='content_topics')
    op.drop_index('ix_content_topics_content', table_name='content_topics')
    op.drop_table('content_topics')
    op.drop_index('ix_content_entities_entity', table_name='content_entities')
    op.drop_index('ix_content_entities_content', table_name='content_entities')
    op.drop_table('content_entities')
    op.drop_index('ix_content_cluster_members_cluster', table_name='content_cluster_members')
    op.drop_table('content_cluster_members')
    op.drop_table('taxonomy_topics')
    op.drop_table('entities')
    op.drop_table('content_scores')
    op.drop_table('content_enrichment')
    op.drop_table('content_clusters')
    # ### end Alembic commands ###
