"""m12_deep_media_chunks_stt_transcript_segments

Revision ID: 86312c40025b
Revises: 694b5a3aa3a4
Create Date: 2026-07-18 17:35:18.602847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86312c40025b'
down_revision: Union[str, Sequence[str], None] = '694b5a3aa3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video' — in practice only 'youtube_video' produces chunks today"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment="0-based order within this item's chunks"),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('chapter_title', sa.String(length=200), nullable=False),
    sa.Column('chunk_summary', sa.Text(), nullable=False),
    sa.Column('summary_version', sa.String(length=50), nullable=False, comment="Prompt/schema version tag (app/agents/chunk_summary_agent.py's CHUNK_SUMMARY_VERSION)"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', 'chunk_index', name='uq_content_chunks_content_index')
    )
    op.create_index('ix_content_chunks_content', 'content_chunks', ['content_type', 'content_id'], unique=False)
    op.create_table('stt_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video' — in practice only 'youtube_video' today"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment="'queued' | 'running' | 'completed' | 'failed' | 'skipped_too_long'"),
    sa.Column('transcript_source', sa.String(length=20), nullable=True, comment="'manual_caption' | 'auto_caption' | 'stt' — set for every video regardless of which path produced its transcript"),
    sa.Column('whisper_model', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'skipped_too_long')", name='ck_stt_jobs_status'),
    sa.CheckConstraint("transcript_source IS NULL OR transcript_source IN ('manual_caption', 'auto_caption', 'stt')", name='ck_stt_jobs_transcript_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', name='uq_stt_jobs_content')
    )
    op.add_column('youtube_videos', sa.Column('transcript_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='[{start, duration, text}, ...] — per-segment timing, same shape whether sourced from YouTube captions or STT (app/services/stt_service.py). NULL for videos scraped before M12 or still pending transcription (see stt_jobs).'))
    op.add_column('youtube_videos', sa.Column('duration_seconds', sa.Integer(), nullable=True, comment="Video length — derived from transcript_segments' last entry (captions) or yt-dlp metadata (STT). Drives both the STT duration ceiling and the long-video tier gate (run_pipeline.py's run_deep_video_phase)."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videos', 'duration_seconds')
    op.drop_column('youtube_videos', 'transcript_segments')
    op.drop_table('stt_jobs')
    op.drop_index('ix_content_chunks_content', table_name='content_chunks')
    op.drop_table('content_chunks')
    # ### end Alembic commands ###
