"""add user_affinities and digest_click_tokens

Revision ID: b3a44ff1b6b1
Revises: baa659940419
Create Date: 2026-07-15 00:24:28.844129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a44ff1b6b1'
down_revision: Union[str, Sequence[str], None] = 'baa659940419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_click_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Django users.id — plain reference, no DB-level FK (different ORM/metadata)'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment="'article' or 'youtube_video'"),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_digest_click_tokens_created_at', 'digest_click_tokens', ['created_at'], unique=False)
    op.create_table('user_affinities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Django users.id — plain reference, no DB-level FK (different ORM/metadata)'),
    sa.Column('dimension', sa.String(length=20), nullable=False, comment="'topic' | 'source' | 'entity' — only 'source' is populated until M8's taxonomy exists"),
    sa.Column('key', sa.String(length=200), nullable=False, comment="The dimension's value, e.g. a Source.key when dimension='source'"),
    sa.Column('weight', sa.Float(), nullable=False, comment='Time-decayed affinity weight, recomputed wholesale per (user, dimension, key) each nightly run'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dimension IN ('topic', 'source', 'entity')", name='ck_user_affinities_dimension'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dimension', 'key', name='uq_user_affinity_dimension_key')
    )
    op.create_index('ix_user_affinities_user_dimension', 'user_affinities', ['user_id', 'dimension'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_affinities_user_dimension', table_name='user_affinities')
    op.drop_table('user_affinities')
    op.drop_index('ix_digest_click_tokens_created_at', table_name='digest_click_tokens')
    op.drop_table('digest_click_tokens')
    # ### end Alembic commands ###
