"""baseline: existing schema

Revision ID: baa659940419
Revises: 
Create Date: 2026-07-14 08:53:23.947666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa659940419'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='Scraper source identifier — see the class docstring for the full list of valid values',
               existing_comment='Scraper source identifier, e.g. blog_openai | blog_anthropic',
               existing_nullable=False)
    op.alter_column('articles', 'image_url',
               existing_type=sa.VARCHAR(length=2048),
               comment="Hero image scraped from the article's og:image tag, if available",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'image_url',
               existing_type=sa.VARCHAR(length=2048),
               comment=None,
               existing_comment="Hero image scraped from the article's og:image tag, if available",
               existing_nullable=True)
    op.alter_column('articles', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='Scraper source identifier, e.g. blog_openai | blog_anthropic',
               existing_comment='Scraper source identifier — see the class docstring for the full list of valid values',
               existing_nullable=False)
    # ### end Alembic commands ###
