# Generated by Django 5.2.16 on 2026-07-14 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('youtube_video', 'YouTube video')], max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('is_saved', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_items',
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'content_id'), name='uq_saved_item')],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('dwell', 'Dwell'), ('scroll', 'Scroll'), ('save', 'Save'), ('hide', 'Hide'), ('search', 'Search'), ('digest_click', 'Digest click')], max_length=20)),
                ('content_type', models.CharField(blank=True, choices=[('article', 'Article'), ('youtube_video', 'YouTube video')], max_length=20, null=True)),
                ('content_id', models.BigIntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, help_text='Numeric payload whose meaning depends on event_type — dwell ms, scroll %, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_events',
                'indexes': [models.Index(fields=['user', 'created_at'], name='ix_user_events_user_created')],
            },
        ),
    ]
