# app/database/models/trend_report.py
#
# Weekly grounded trend narrative (M11, Pro) — generated by
# app/agents/trend_narrative_agent.py::TrendNarrativeAgent and persisted by
# app/tasks/trend_tasks.py::generate_weekly_trend_report_task (its own
# Monday beat entry — the only genuinely weekly, LLM-driven job in this
# milestone; burst detection itself is LLM-free and rides the existing
# 6-hourly pipeline chain instead).
#
# `narrative` is a JSONB list of claim-units, NOT free prose — each unit is
# {headline, body, trend_dimension, trend_key, citations: [{content_type,
# content_id}, ...]} — so "cite every claim" (the roadmap's own risk-register
# wording) is mechanically checkable rather than a matter of trusting the
# LLM. Citations are resolved server-side from short prompt handles
# ([S1], [S2], ...) rather than the LLM reproducing real integer ids from
# memory — see TrendNarrativeAgent's docstring for why. Any claim-unit whose
# citations are empty after resolution is dropped before this row is ever
# written — a claim with zero real citations is by definition unsupported.
#
# `raw_narrative` keeps the PRE-filter LLM output (never rendered to users)
# so a human can spot-check what got cut — this milestone auto-publishes
# (matches every other LLM output in this app; no draft/review gate exists
# anywhere in this codebase, confirmed before choosing this design), so this
# audit trail is the actual safety net, not a moderation queue.

from datetime import date as date_type, datetime

from sqlalchemy import JSON, BigInteger, Date, DateTime, String, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base


class TrendReport(Base):
    __tablename__ = "trend_reports"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    week_start_date: Mapped[date_type] = mapped_column(Date, nullable=False, comment="Monday of the covered week (UTC)")

    narrative: Mapped[list] = mapped_column(
        JSON().with_variant(JSONB(), "postgresql"), nullable=False, default=list,
        comment="List of claim-units shown to users: {headline, body, trend_dimension, trend_key, citations: [{content_type, content_id}, ...]}",
    )
    raw_narrative: Mapped[list | None] = mapped_column(
        JSON().with_variant(JSONB(), "postgresql"), nullable=True, default=None,
        comment="Pre-grounding-filter LLM output, for spot-check auditing only — never rendered to users",
    )
    narrative_version: Mapped[str] = mapped_column(String(50), nullable=False, comment="Prompt/schema version, same convention as EnrichmentAgent's enrichment_version")
    llm_model: Mapped[str] = mapped_column(String(100), nullable=False)

    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    __table_args__ = (
        UniqueConstraint("week_start_date", name="uq_trend_reports_week_start_date"),
    )

    def __repr__(self) -> str:
        return f"<TrendReport week_start_date={self.week_start_date} claims={len(self.narrative or [])}>"
