# Generated by Django 5.2.16 on 2026-07-14 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contentcluster_contentclustermember_and_more'),
        ('onboarding', '0002_seed_lookups'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='taxonomy_topic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='catalog.taxonomytopic'),
        ),
    ]
