# Generated by Django 5.2.15 on 2026-07-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_link_taxonomy_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdigestsettings',
            name='format_balance',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('articles', 'Prefer articles'), ('videos', 'Prefer videos')], default='balanced', help_text='Soft nudge on article vs. video mix in ranked results — never a hard filter.', max_length=20),
        ),
        migrations.AddField(
            model_name='userdigestsettings',
            name='reading_time_budget_minutes',
            field=models.IntegerField(blank=True, help_text='Soft per-item time budget the ranker penalizes (not excludes) items against. Blank = no budget.', null=True),
        ),
        migrations.AddField(
            model_name='userdigestsettings',
            name='topic_lean',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('research', 'Research-leaning'), ('industry', 'Industry-leaning')], default='balanced', help_text='Nudges ranking toward research-paper-style vs. product/industry-news content_category groupings.', max_length=20),
        ),
    ]
