# Generated by Django 5.2.15 on 2026-07-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_plan_user_plan_expires_at'),
        ('catalog', '0006_personentity'),
        ('onboarding', '0005_userdigestsettings_format_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSourceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_subscriptions', to='accounts.userprofile')),
                ('source', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='catalog.source')),
            ],
            options={
                'db_table': 'user_source_subscriptions',
                'constraints': [models.UniqueConstraint(fields=('profile', 'source'), name='uq_profile_source_subscription')],
            },
        ),
    ]
