# Generated by Django 5.2.15 on 2026-06-24 09:40

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=2048, unique=True)),
                ('source', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'db_table': 'articles',
                'ordering': ['-published_at'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=2048, unique=True)),
                ('source', models.CharField(default='youtube', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'YouTube video',
                'verbose_name_plural': 'YouTube videos',
                'db_table': 'youtube_videos',
                'ordering': ['-published_at'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
