# Generated by Django 5.2.16 on 2026-07-13 06:12

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'digest log entry',
                'verbose_name_plural': 'digest log entries',
                'db_table': 'digest_log',
                'ordering': ['-sent_at'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('adapter_type', models.CharField(max_length=20)),
                ('handler', models.CharField(blank=True, max_length=50, null=True)),
                ('config', models.JSONField(default=dict)),
                ('schedule_hours', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'db_table': 'sources',
                'ordering': ['category', 'name'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='UserRanking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('rank', models.IntegerField()),
                ('relevance_score', models.FloatField()),
                ('reasoning', models.TextField(blank=True, default='')),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'user ranking',
                'verbose_name_plural': 'user rankings',
                'db_table': 'user_rankings',
                'ordering': ['rank'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
