# Generated by Django 5.2.16 on 2026-07-14 21:26

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_digestlog_source_userranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestClickToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'digest click token',
                'verbose_name_plural': 'digest click tokens',
                'db_table': 'digest_click_tokens',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='UserAffinity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'user affinity',
                'verbose_name_plural': 'user affinities',
                'db_table': 'user_affinities',
                'ordering': ['-weight'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
