# Generated by Django 5.2.16 on 2026-07-14 23:48

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_digestclicktoken_useraffinity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'content cluster',
                'verbose_name_plural': 'content clusters',
                'db_table': 'content_clusters',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ContentClusterMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('similarity_to_centroid', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'content cluster member',
                'verbose_name_plural': 'content cluster members',
                'db_table': 'content_cluster_members',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ContentEnrichment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('content_category', models.CharField(max_length=30)),
                ('technical_depth', models.IntegerField()),
                ('key_points', models.JSONField(default=list)),
                ('technical_details', models.TextField(blank=True, default='')),
                ('business_angle', models.TextField(blank=True, default='')),
                ('why_it_matters', models.TextField(blank=True, default='')),
                ('enrichment_version', models.CharField(max_length=50)),
                ('enriched_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'content enrichment',
                'verbose_name_plural': 'content enrichment',
                'db_table': 'content_enrichment',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ContentEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('mention_context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'content entity',
                'verbose_name_plural': 'content entities',
                'db_table': 'content_entities',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ContentScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('score', models.FloatField()),
                ('score_version', models.CharField(max_length=50)),
                ('features', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'content score',
                'verbose_name_plural': 'content scores',
                'db_table': 'content_scores',
                'ordering': ['-score'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='ContentTopic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'content topic',
                'verbose_name_plural': 'content topics',
                'db_table': 'content_topics',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('entity_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'db_table': 'entities',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='TaxonomyTopic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'taxonomy topic',
                'verbose_name_plural': 'taxonomy topics',
                'db_table': 'taxonomy_topics',
                'ordering': ['sort_order', 'name'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
