# Generated by Django 5.2.15 on 2026-07-15 02:52

import apps.catalog.models
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contentcluster_contentclustermember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'embedding',
                'verbose_name_plural': 'embeddings',
                'db_table': 'embeddings',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
