# Generated by Django 5.2.15 on 2026-07-15 19:22

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('footprint_type', models.CharField(max_length=20)),
                ('external_identifier', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'person entity',
                'verbose_name_plural': 'person entities',
                'db_table': 'person_entities',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
