# Generated by Django 5.2.16 on 2026-07-17 16:53

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_personentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mention_count', models.IntegerField()),
                ('baseline_mean', models.FloatField()),
                ('baseline_stddev', models.FloatField()),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('is_trending', models.BooleanField()),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'trend',
                'verbose_name_plural': 'trends',
                'db_table': 'trends',
                'ordering': ['-date', '-z_score'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='TrendReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('narrative', models.JSONField()),
                ('raw_narrative', models.JSONField(blank=True, null=True)),
                ('narrative_version', models.CharField(max_length=50)),
                ('llm_model', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'trend report',
                'verbose_name_plural': 'trend reports',
                'db_table': 'trend_reports',
                'ordering': ['-week_start_date'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
