# Generated by Django 5.2.16 on 2026-07-18 14:34

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_trend_trendreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('chunk_index', models.IntegerField()),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('chapter_title', models.CharField(max_length=200)),
                ('chunk_summary', models.TextField()),
                ('summary_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'content chunk',
                'verbose_name_plural': 'content chunks',
                'db_table': 'content_chunks',
                'ordering': ['content_type', 'content_id', 'chunk_index'],
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
        migrations.CreateModel(
            name='SttJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('transcript_source', models.CharField(blank=True, max_length=20, null=True)),
                ('whisper_model', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'STT job',
                'verbose_name_plural': 'STT jobs',
                'db_table': 'stt_jobs',
                'managed': False,
            },
            bases=(apps.catalog.models.ReadOnly, models.Model),
        ),
    ]
